// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: shipping.proto

package shipping

import (
	context "context"
	common "create-order-saga/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingServiceClient interface {
	// Arranges shipping for an order.
	ArrangeShipping(ctx context.Context, in *ArrangeShippingRequest, opts ...grpc.CallOption) (*ArrangeShippingResponse, error)
	// Cancels a previously arranged shipment (compensation action).
	CancelShipping(ctx context.Context, in *CancelShippingRequest, opts ...grpc.CallOption) (*common.CompensationResponse, error)
}

type shippingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingServiceClient(cc grpc.ClientConnInterface) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) ArrangeShipping(ctx context.Context, in *ArrangeShippingRequest, opts ...grpc.CallOption) (*ArrangeShippingResponse, error) {
	out := new(ArrangeShippingResponse)
	err := c.cc.Invoke(ctx, "/shipping.ShippingService/ArrangeShipping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) CancelShipping(ctx context.Context, in *CancelShippingRequest, opts ...grpc.CallOption) (*common.CompensationResponse, error) {
	out := new(common.CompensationResponse)
	err := c.cc.Invoke(ctx, "/shipping.ShippingService/CancelShipping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
// All implementations must embed UnimplementedShippingServiceServer
// for forward compatibility
type ShippingServiceServer interface {
	// Arranges shipping for an order.
	ArrangeShipping(context.Context, *ArrangeShippingRequest) (*ArrangeShippingResponse, error)
	// Cancels a previously arranged shipment (compensation action).
	CancelShipping(context.Context, *CancelShippingRequest) (*common.CompensationResponse, error)
	mustEmbedUnimplementedShippingServiceServer()
}

// UnimplementedShippingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShippingServiceServer struct {
}

func (UnimplementedShippingServiceServer) ArrangeShipping(context.Context, *ArrangeShippingRequest) (*ArrangeShippingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArrangeShipping not implemented")
}
func (UnimplementedShippingServiceServer) CancelShipping(context.Context, *CancelShippingRequest) (*common.CompensationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelShipping not implemented")
}
func (UnimplementedShippingServiceServer) mustEmbedUnimplementedShippingServiceServer() {}

// UnsafeShippingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingServiceServer will
// result in compilation errors.
type UnsafeShippingServiceServer interface {
	mustEmbedUnimplementedShippingServiceServer()
}

func RegisterShippingServiceServer(s grpc.ServiceRegistrar, srv ShippingServiceServer) {
	s.RegisterService(&ShippingService_ServiceDesc, srv)
}

func _ShippingService_ArrangeShipping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArrangeShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ArrangeShipping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping.ShippingService/ArrangeShipping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ArrangeShipping(ctx, req.(*ArrangeShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_CancelShipping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CancelShipping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping.ShippingService/CancelShipping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CancelShipping(ctx, req.(*CancelShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingService_ServiceDesc is the grpc.ServiceDesc for ShippingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipping.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ArrangeShipping",
			Handler:    _ShippingService_ArrangeShipping_Handler,
		},
		{
			MethodName: "CancelShipping",
			Handler:    _ShippingService_CancelShipping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping.proto",
}
